avalanche_binaries_dir: "{{ repo_folder }}/build"
repo_folder: "~{{ ansible_facts.user_id }}/go/src/github.com/haowang0402/avalanchego"
repo_name: haowang0402/avalanchego
repo_url: https://github.com/{{ repo_name }}
repo_branch: dev
